# Generated by Django 6.0.4 on 2026-04-21 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_id', models.CharField(max_length=10)),
                ('text', models.TextField(max_length=300)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('done', models.BooleanField(default=False)),
                ('problem_id', models.CharField(max_length=10)),
                ('title', models.TextField()),
                ('rating', models.IntegerField()),
                ('problem_link', models.URLField()),
                ('solution_link', models.URLField()),
                ('star', models.BooleanField(default=False)),
                ('notes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sheet.notes')),
            ],
        ),
    ]
