# Generated by Django 6.0.4 on 2026-04-26 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField(max_length=20)),
                ('last_name', models.TextField(max_length=20)),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=20)),
                ('handle', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('country', models.CharField(max_length=15)),
                ('current_role', models.TextField(max_length=50)),
                ('bio', models.TextField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_id', models.CharField(max_length=10)),
                ('title', models.TextField(max_length=100)),
                ('rating', models.IntegerField()),
                ('problem_link', models.URLField()),
                ('solution_link', models.URLField(blank=True)),
                ('star', models.BooleanField(default=False)),
                ('category', models.CharField(choices=[('<1300', '<1300'), ('<1500', '<1500'), ('<1700', '<1700')], default='Unrated', max_length=7)),
                ('notes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sheet.notes')),
            ],
        ),
        migrations.DeleteModel(
            name='questions',
        ),
    ]
