# Generated by Django 6.0.4 on 2026-06-04 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='problem_id',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='sheet_question',
            name='problem_id',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
