# Generated by Django 6.0.4 on 2026-06-06 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0002_alter_question_problem_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='star',
            name='is_star',
        ),
    ]
