# Generated by Django 6.0.4 on 2026-06-06 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0003_remove_star_is_star'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='problem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sheet.sheet_question'),
        ),
        migrations.AlterField(
            model_name='star',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sheet.sheet_question'),
        ),
    ]
